[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"

# replace-with = 'ustc'
# replace-with = 'rustcc'

[source.ustc]
registry = "https://mirrors.ustc.edu.cn/crates.io-index"

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"

[source.rustcc]
registry = "git://crates.rustcc.cn/crates.io-index"

[net]
git-fetch-with-cli = true