[application]
name = "Dioxus App"
default_platform = "desktop"
asset_dir = "public"
# 发布相关
# out_dir = "dist"
# base_path = "your_repo"

[web.app]
title = "Dioxus Web App"

[web.watcher]
reload_html = true
# watch_path = ["src/**/*"]

[web.resource]
style = [
    "style.css"
]

[web.resource.dev]
style = [
    "style.css"
]